"""Migrate to flask_sqlalchemy and refactor interaction table

Revision ID: 17f9f9c3ca5d
Revises: a3a1d21d3fdd
Create Date: 2024-06-02 16:07:23.960257

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17f9f9c3ca5d'
down_revision = 'a3a1d21d3fdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_interactions_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_interaction_type'), ['interaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_user_id'), ['user_id'], unique=False)
        batch_op.drop_column('reward')

    with op.batch_alter_table('reading_history', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'content', ['book_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward', mysql.FLOAT(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_interactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_interactions_interaction_type'))
        batch_op.drop_index(batch_op.f('ix_interactions_content_id'))
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
