"""Add book_parameters table

Revision ID: 50c4cc7c1c7d
Revises: 8a8ec8e5c811
Create Date: 2024-06-13 23:45:36.192099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c4cc7c1c7d'
down_revision = '8a8ec8e5c811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('parameters', sa.PickleType(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_parameters')
    # ### end Alembic commands ###
