"""Remove book type

Revision ID: b205527ace9b
Revises: 7dec079034b4
Create Date: 2024-07-07 21:44:59.821461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b205527ace9b'
down_revision = '7dec079034b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.ENUM('book', 'article'), nullable=True))

    # ### end Alembic commands ###
